name: Lineosaurus
description: Let's count!
author: Nicholas Valentinus
branding:
  icon: align-justify
  color: gray-dark

inputs:
  git-name:
    description: Git name
  git-email:
    description: Git email
  show-credit:
    description: Show the credit
    default: true
  only-type:
    description: "['.py', '.js']"
    default: null
  ignore-type:
    description: "['.py', '.js']"
    default: null
  header:
    description: Header
    default: null
  footer:
    description: Footer
    default: null
  custom-title:
    description: Title
    default: null
  num-shown:
    description: Number
    default: 5
  show-approx:
    description: Approx
    default: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/src/cloning.sh
      shell: bash
    - uses: actions/checkout@v3
    - run: python $GITHUB_ACTION_PATH/src run
      shell: bash
      env:
        SHOW_CREDIT: ${{ inputs.show-credit }}
        ONLY_TYPE: ${{ inputs.only-type }}
        IGNORE_TYPE: ${{ inputs.ignore-type }}
        HEADER: ${{ inputs.header }}
        FOOTER: ${{ inputs.footer }}
        CUSTOM_TITLE: ${{ inputs.custom-title }}
        NUM_SHOWN: ${{ inputs.num-shown }}
        SHOW_APPROX: ${{ inputs.show-approx }}
    - uses: scapeville/action-git-add-all-then-commit-then-push@v1
      with:
        name: ${{ env.git-name }}
        email: ${{ env.git-email }}
        msg: "Updated on $(date +'%Y %b %e, %l:%M %p')"