name: lineosaurus
description: let's count
author: Nicholas Valentinus
branding:
  icon: align-justify
  color: gray-dark

inputs:
  git-name:
    description: Git name
  git-email:
    description: Git email
  show-credit:
    description: show the credit
    default: true
  only_type:
    description: "['.py', '.js']"
    default: null
  ignore_type:
    description: "['.py', '.js']"
    default: null
  header:
    description: Header
    default: null
  footer:
    description: Footer
    default: null
  custom-title:
    description: Title
    default: null
  num-shown:
    description: Number
    default: 5
  show-approx:
    description: Approx
    default: true

runs:
  using: 'composite'
  steps:      
    - shell: bash
      run: |
        RAW=$(gh repo list $GITHUB_ACTOR --visibility public --json url)
        NUM=$(python $GITHUB_ACTION_PATH/src get-num-repos $RAW)
        URLS=$(python $GITHUB_ACTION_PATH/src get-clone-urls $RAW)

        echo "::group::DEBUG: RAW:"
        echo $RAW
        echo "::endgroup::"
        echo "::group::DEBUG"
        echo "NUM: '$NUM'"
        for url in $URLS; do
          echo "URL: '$url'"
        done
        echo "::endgroup::"

        echo "::group::Cloning"
        ## Folder to store all the cloned repositories
        mkdir $GITHUB_WORKSPACE/../workspace
        cd $GITHUB_WORKSPACE/../workspace


        echo "::endgroup::"

        # echo "::group::ls $(pwd)"
        # ls
        # echo "::endgroup::"

        # for url in $URLS; do
        #   git clone $url
        # done

        # echo "::group::ls $(pwd)"
        # ls
        # echo "::endgroup::"
    # - uses: actions/checkout@v3
    # - shell: bash
    #   run: ls
    # - uses: scapeville/action-git-add-all-then-commit-then-push@v1
    #   with:
    #     name: ${{ env.git-name }}
    #     email: ${{ env.git-email }}
    #     msg: "Updated on $(date +'%Y %b %e, %l:%M %p')"