name: Lineosaurus
description: Let's count!
author: Nicholas Valentinus
branding:
  icon: align-justify
  color: gray-dark

inputs:
  git-name:
    description: Git name
    required: true
  git-email:
    description: Git email
    required: true
  only-type:
    description: "['.py', '.js']"
    default: null  # Note: in YAML, `null` becomes `''` in Python.
  ignore-type:
    description: "['.py', '.js']"
    default: null
  header:
    description: Header (relative to repo root)
    default: null
  footer:
    description: Footer
    default: null
  custom-title:
    description: Title
    default: null
  num-shown:
    description: Number
    default: 5
  show-approx:
    description: Approx
    default: true
  card-titles:
    description: card titles
    default: null
  card-order:
    description: card order
    default: null
  show-credit:
    description: show the credit
    default: true

runs:
  using: 'composite'
  steps:      
    - run: pip install mykit==6.0.0
      shell: bash
    - run: $GITHUB_ACTION_PATH/src/cloning.sh
      shell: bash
    - uses: actions/checkout@v3
    - run: python $GITHUB_ACTION_PATH/src run
      shell: bash
      env:
        ONLY_TYPE: ${{ inputs.only-type }}
        IGNORE_TYPE: ${{ inputs.ignore-type }}
        HEADER: ${{ inputs.header }}
        FOOTER: ${{ inputs.footer }}
        CUSTOM_TITLE: ${{ inputs.custom-title }}
        NUM_SHOWN: ${{ inputs.num-shown }}
        SHOW_APPROX: ${{ inputs.show-approx }}
        CARD_TITLES: ${{ inputs.card-titles }}
        CARD_ORDER: ${{ inputs.card-order }}
        SHOW_CREDIT: ${{ inputs.show-credit }}
    - uses: scapeville/action-git-add-all-then-commit-then-push@v1
      with:
        name: ${{ inputs.git-name }}
        email: ${{ inputs.git-email }}
        msg: "Updated on $(date +'%Y %b %e, %l:%M %p')"