# .github/workflows/execushell.yml

name: ExecuShell

on: workflow_dispatch  # Run manually from 'Actions' tab

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: scapeville/action-ExecuShell@v1
        with:
          dir: ./src
          git-name: your name
          git-email: your@email
          recursive: false